### ISSUE TITLE
JDK提示版本太低。

### ISSUE THREAD

**Issue by wohelu666** [xluu233/mvvm_develop#1]
Could not target platform: 'Java SE 11' using tool chain: 'JDK 8 (1.8)'.

**Comment by xluu233** [comment]
setting中搜索gradle，更改GradleJDK版本为java11
![QQ截图20211221145335](https://user-images.githubusercontent.com/36953440/146885307-cd2617b7-a748-43b2-8558-79b349d8fefa.png)

**Comment by wohelu666** [comment]
![image](https://user-images.githubusercontent.com/48713628/146885863-28936372-3898-4a57-bccd-d591cc3ddf65.png)
没找到有这个选项

**Comment by wohelu666** [comment]
不行哦，运行不起来，更换JDK版本也没用。

**Comment by xluu233** [comment]
😲感觉是gradle配置的问题

**Comment by wohelu666** [comment]
我as 4.0.0的，gradle 6.1.1.

**Comment by xluu233** [comment]
#### 要求gradle7.0以上
![QQ截图20211221170624](https://user-images.githubusercontent.com/36953440/146902540-34ee2768-6f44-4459-94e5-c98c80ff6600.png)
